// <auto-generated />
namespace F2021A6MO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class beforePublish : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(beforePublish));
        
        string IMigrationMetadata.Id
        {
            get { return "202112102055140_beforePublish"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
